_core:
  default_config_hash: KsPFWSp6mgXIQgjBJEShfKUGn6VLRlbpIJ2EysXvXWM
langcode: ru
access_token_expiration: 9999
authorization_code_expiration: 9999
refresh_token_expiration: 1209600
token_cron_batch_size: 0
public_key: /var/www/public.key
private_key: /var/www/private.key
remember_clients: true
use_implicit: false
disable_openid_connect: false
